name: run install script

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths:
      - 'scripts/ubuntu.sh'
      - '.github/workflows/install_script.yml'

jobs:
  run_install_script:
    strategy: 
      matrix:
        branch: ['develop', 'stable'] # 'develop' can be anything that's not 'stable'. This triggers an if statement in ubuntu.sh
        build_hdf5: ['NO', 'hdf5-1_12_0']
        os: ['ubuntu-latest', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: run install script
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/scripts
          chmod +x ubuntu.sh
          ./ubuntu.sh ${{ matrix.branch }} ${{ matrix.build_hdf5 }}

      # use matrix to have 2 jobs [develop, stable]
      # ./ubuntu.sh stable

